config/routes.rb
HelloWorldTests::Application.routes.draw do

  root :to => "home#index"
  get 'admin' => "auth_admin#index"

  controller :auth_sessions do
    get 'auth_login' => :new
    post 'auth_login' => :create
    delete 'auth_logout' => :destroy
    get 'auth_logout' => :destroy
  end

  resources :auth_users
  resources :shop_items, :google_map, :shop_carts
  resources :user_orders
  resources :cars
  resources :fb_users, :only => [:index]
  resources :frogs
  resources :my_test_scaffolds do
    get :who_bought_this, :on => :member
  end

  match 'svetik/home' => 'svetik#home'
  match 'say/hello' => 'say#hello'
  match 'say/goodbye' => 'say#goodbye'
  match 'my_store' => 'my_store#index'
  match 'resque_que' => 'resque_que#index'
  mount Resque::Server, :at => "/resque"
end

app/models/my_test_scaffold.rb
class MyTestScaffold < ActiveRecord::Base
  # It will be aplied all queries of this model
  default_scope :order => 'title'
  # Reference for items in carts
  has_many :shop_items
  has_many :user_orders, :through => :shop_items

  # Images
  has_attached_file :image

  # Prevent delete is any item in a cart has reference
  before_destroy :no_shop_item

  validates :title, :description, :presence => true
  validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
  validates :title, :uniqueness => { :message => 'has already been taken. Should be unique.' }

  def no_shop_item
    return true if shop_items.count.zero?
    errors[:base] << "Shop Items present"
    return false
  end
end

app/controllers/my_test_scaffolds_controller.rb
class MyTestScaffoldsController < ApplicationController
  layout 'my_book_store'
  before_filter :admin_authorize

  # GET /my_test_scaffolds
  # GET /my_test_scaffolds.xml
  def index
    @my_test_scaffolds = MyTestScaffold.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @my_test_scaffolds }
    end
  end

  # GET /my_test_scaffolds/1
  # GET /my_test_scaffolds/1.xml
  def show
    @my_test_scaffold = MyTestScaffold.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @my_test_scaffold }
    end
  end

  # GET /my_test_scaffolds/new
  # GET /my_test_scaffolds/new.xml
  def new
    @my_test_scaffold = MyTestScaffold.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @my_test_scaffold }
    end
  end

  # GET /my_test_scaffolds/1/edit
  def edit
    @my_test_scaffold = MyTestScaffold.find(params[:id])
  end

  # POST /my_test_scaffolds
  # POST /my_test_scaffolds.xml
  def create
    @my_test_scaffold = MyTestScaffold.new(params[:my_test_scaffold])

    respond_to do |format|
      if @my_test_scaffold.save
        format.html { redirect_to(@my_test_scaffold, :notice => 'My test scaffold was successfully created.') }
        format.xml  { render :xml => @my_test_scaffold, :status => :created, :location => @my_test_scaffold }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @my_test_scaffold.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /my_test_scaffolds/1
  # PUT /my_test_scaffolds/1.xml
  def update
    @my_test_scaffold = MyTestScaffold.find(params[:id])

    respond_to do |format|
      if @my_test_scaffold.update_attributes(params[:my_test_scaffold])
        format.html { redirect_to(@my_test_scaffold, :notice => 'My test scaffold was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @my_test_scaffold.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /my_test_scaffolds/1
  # DELETE /my_test_scaffolds/1.xml
  def destroy
    @my_test_scaffold = MyTestScaffold.find(params[:id])
    @my_test_scaffold.destroy

    respond_to do |format|
      format.html { redirect_to(my_test_scaffolds_url) }
      format.xml  { head :ok }
    end
  end

  def who_bought_this
    @my_test_scaffold = MyTestScaffold.find(params[:id])

    respond_to do |format|
      format.atom # see ../views/who_bought_this.atom.builder
#      format.xml { render :xml => @my_test_scaffold }
      format.xml
      format.html
    end
  end
end

app/views/my_test_scaffolds/_form.html.erb
<%= form_for @my_test_scaffold, :validate => true, :html => {:multipart => true} do |f| %>
  <% if @my_test_scaffold.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@my_test_scaffold.errors.count, "error") %> prohibited this my_test_scaffold from being saved:</h2>

      <ul>
      <% @my_test_scaffold.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows => 6 %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
<% end %>

<script>
  function formSubmit(id) {

    // Any JS you want before submit

    // Submit
    document.getElementById(id).submit();

  }
</script>

app/views/my_test_scaffolds/edit.html.erb
<h1>Editing my_test_scaffold</h1>

<%= render 'form' %>
<div class="actions">
  <input type="button" onclick="formSubmit('edit_my_test_scaffold_<%= @my_test_scaffold.id %>')" value="Update a book">
</div>

<%= link_to 'Show', @my_test_scaffold %> |
<%= link_to 'Back', my_test_scaffolds_path %>

app/views/my_test_scaffolds/index.html.erb
<div id="product_list">

<h1>Listing my_test_scaffolds</h1>

<table>

<% @my_test_scaffolds.each do |my_test_scaffold| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
    <td><%= image_tag(my_test_scaffold.image.url, :class => 'list_image') %></td>

    <td class="list_description">
      <dl>
        <dt><%= my_test_scaffold.title %></dt>
        <dd><%= truncate(strip_tags(my_test_scaffold.description), :length => 80) %><br/>
        <%= currency(my_test_scaffold.price) %></dd>
      </dl>
    </td>

    <td class="list_actions">
      <%= link_to 'Show', my_test_scaffold %><br/>
      <%= link_to 'Edit', edit_my_test_scaffold_path(my_test_scaffold) %><br/>
      <%= link_to 'Who Bought This', { :controller => 'my_test_scaffolds', :action => 'who_bought_this', :id => my_test_scaffold.id } %><br/>
      <%= link_to 'Destroy', my_test_scaffold, :confirm => 'Are you sure?', :method => :delete %>
    </td>
  </tr>
<% end %>
</table>

</div>

<br />

<%= link_to 'Add new book', new_my_test_scaffold_path %>

app/views/my_test_scaffolds/new.html.erb
<h1>New my_test_scaffold</h1>

<%= render 'form' %>
<div class="actions">
  <input type="button" onclick="formSubmit('new_my_test_scaffold')" value="Create a book">
</div>

<%= link_to 'Back', my_test_scaffolds_path %>

app/views/my_test_scaffolds/show.html.erb
<!--<p id="notice"><%= notice %></p>-->

<p>
  <b>Title:</b>
  <%= @my_test_scaffold.title %>
</p>

<p>
  <b>Description:</b>
  <%= @my_test_scaffold.description %>
</p>

<p>
  <b>Image:</b><br/>
  <%= image_tag @my_test_scaffold.image.url %>
</p>

<p>
  <b>Price:</b>
  <%= @my_test_scaffold.price %>
</p>


<%= link_to 'Edit', edit_my_test_scaffold_path(@my_test_scaffold) %> |
<%= link_to 'Back', my_test_scaffolds_path %>