config/routes.rb
HelloWorldTests::Application.routes.draw do

  root :to => "home#index"
  get 'admin' => "auth_admin#index"

  controller :auth_sessions do
    get 'auth_login' => :new
    post 'auth_login' => :create
    delete 'auth_logout' => :destroy
    get 'auth_logout' => :destroy
  end

  resources :auth_users
  resources :shop_items, :google_map, :shop_carts
  resources :user_orders
  resources :cars
  resources :fb_users, :only => [:index]
  resources :frogs
  resources :my_test_scaffolds do
    get :who_bought_this, :on => :member
  end

  match 'svetik/home' => 'svetik#home'
  match 'say/hello' => 'say#hello'
  match 'say/goodbye' => 'say#goodbye'
  match 'my_store' => 'my_store#index'
  match 'resque_que' => 'resque_que#index'
  mount Resque::Server, :at => "/resque"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/views/home/index.html.erb
<h1 align="center">Home#index</h1>
<p><%= link_to "Google Maps", google_map_index_path %></p>
<p><%= link_to "My Store", my_store_path %></p>
<p><%= link_to "My Test Scaffold (Admin of the store)", my_test_scaffolds_path %></p>
<p><%= link_to "Svetik Home", svetik_home_path %></p>
<p><%= link_to "Say Hello", say_hello_path %></p>
<p><%= link_to "Say Goodbye", say_goodbye_path %></p>
<p><%= link_to "Resque Que", resque_que_path %></p>
<p><%= link_to "Cars to play with state machine and ajax", cars_path %></p>
<p><%= link_to "Page that requires FB login", fb_users_path %></p>
<p><%= link_to "Frogs on Backbone.js", frogs_path %></p>