config/routes.rb
HelloWorldTests::Application.routes.draw do

  root :to => "home#index"
  get 'admin' => "auth_admin#index"

  controller :auth_sessions do
    get 'auth_login' => :new
    post 'auth_login' => :create
    delete 'auth_logout' => :destroy
    get 'auth_logout' => :destroy
  end

  resources :auth_users
  resources :shop_items, :google_map, :shop_carts
  resources :user_orders
  resources :cars
  resources :fb_users, :only => [:index]
  resources :frogs
  resources :my_test_scaffolds do
    get :who_bought_this, :on => :member
  end

  match 'svetik/home' => 'svetik#home'
  match 'say/hello' => 'say#hello'
  match 'say/goodbye' => 'say#goodbye'
  match 'my_store' => 'my_store#index'
  match 'resque_que' => 'resque_que#index'
  mount Resque::Server, :at => "/resque"
end

app/models/shop_cart.rb
class ShopCart < ActiveRecord::Base
  has_many :shop_items, :dependent => :destroy

  def add_test_scaffold(mts_id)
    current_shop_item = shop_items.where(:my_test_scaffold_id => mts_id).first
    if current_shop_item
      current_shop_item.quantity += 1
    else
      current_shop_item = ShopItem.new(:my_test_scaffold_id => mts_id)
      shop_items << current_shop_item
    end
    current_shop_item
  end

  def total_price
    shop_items.to_a.sum { |si| si.total_price }
  end

  def total_shop_items
    shop_items.sum(:quantity)
  end

end

app/controllers/shop_carts_controller.rb
class ShopCartsController < ApplicationController
  layout 'my_book_store'
  # GET /shop_carts
  # GET /shop_carts.xml
  def index
    @shop_carts = ShopCart.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @shop_carts }
    end
  end

  # GET /shop_carts/1
  # GET /shop_carts/1.xml
  def show
    begin
      @shop_cart = ShopCart.find(params[:id])
      # Handle invalid id, ususally in case it's entered manually
    rescue ActiveRecord::RecordNotFound
      logger.error "=========> Attempt to acces invalid Shop Cart, id: #{params[:id]}"
      redirect_to my_store_url, :notice => 'Invalid shop cart'
    else
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @shop_cart }
      end
    end
  end

  # GET /shop_carts/new
  # GET /shop_carts/new.xml
  def new
    @shop_cart = ShopCart.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @shop_cart }
    end
  end

  # GET /shop_carts/1/edit
  def edit
    @shop_cart = ShopCart.find(params[:id])
  end

  # POST /shop_carts
  # POST /shop_carts.xml
  def create
    @shop_cart = ShopCart.new(params[:shop_cart])

    respond_to do |format|
      if @shop_cart.save
        format.html { redirect_to(@shop_cart, :notice => 'Shop cart was successfully created.') }
        format.xml  { render :xml => @shop_cart, :status => :created, :location => @shop_cart }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @shop_cart.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /shop_carts/1
  # PUT /shop_carts/1.xml
  def update
    @shop_cart = ShopCart.find(params[:id])

    respond_to do |format|
      if @shop_cart.update_attributes(params[:shop_cart])
        format.html { redirect_to(@shop_cart, :notice => 'Shop cart was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @shop_cart.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /shop_carts/1
  # DELETE /shop_carts/1.xml
  def destroy
    @shop_cart = ShopCart.find(params[:id])
    @shop_cart.destroy
    session[:shop_cart_id] = nil


    respond_to do |format|
      format.html { redirect_to(my_store_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/shop_carts/_form.html.erb
<%= form_for(@shop_cart) do |f| %>
  <% if @shop_cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shop_cart.errors.count, "error") %> prohibited this shop_cart from being saved:</h2>

      <ul>
      <% @shop_cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shop_carts/_shop_cart.html.erb
<!--
  Partial template. Based on ./show.html.erb.
  It will be used from ../layouts/my_book_store_.html.erb
  Like in any other partial we have here var_name in accrodance with filename _var_name.html.erb
-->

<table>
  <%= render(shop_cart.shop_items) %>  <!-- see patial template ../shop_items/_shop_item.html.erb -->

  <tr class="cart_total_row">
    <td colspan="2">Total</td>
    <td class="cart_total_price"><%= number_to_currency shop_cart.total_price %></td>
  </tr>
  <tr><td colspan="3"><%= button_to 'Checkout', new_user_order_url, :method => :get, :disabled => @disable_checkout_button ? true : false  %></td></tr>
  <tr><td colspan="3"><%= button_to 'Remove all items from cart', shop_cart, :method => :delete, :confirm => 'It will remove all items from the cart. OK?' %></td></tr>

</table>

app/views/shop_carts/edit.html.erb
<h1>Editing shop_cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @shop_cart %> |
<%= link_to 'Back', shop_carts_path %>

app/views/shop_carts/index.html.erb
<h1>Listing shop_carts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shop_carts.each do |shop_cart| %>
  <tr>
    <td><%= link_to 'Show', shop_cart %></td>
    <td><%= link_to 'Edit', edit_shop_cart_path(shop_cart) %></td>
    <td><%= link_to 'Destroy', shop_cart, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Shop cart', new_shop_cart_path %>

app/views/shop_carts/new.html.erb
<h1>New shop_cart</h1>

<%= render 'form' %>

<%= link_to 'Back', shop_carts_path %>

app/views/shop_carts/show.html.erb
<h2 class="shop_cart_title">Shop Cart</h2>
<% if notice %><p id="notice"><%= notice %></p><% end %>

<table>
  <%= render(@shop_cart.shop_items) %> <!-- for shop_item in @shop_cart.shop_items -->
  <!-- see patial template ../shop_items/_shop_item.htnl.erb -->

  <tr class="cart_total_row">
    <td colspan="2">Total</td>
    <td class="cart_total_price"><%= number_to_currency @shop_cart.total_price %></td>
  </tr>
</table>

<%= button_to 'Checkout', user_orders_url, :method => :get %>
<%= button_to 'Remove all items from cart', @shop_cart, :method => :delete, :confirm => 'It will remove all items from the cart. OK?'%>
<!--<%= link_to 'Edit', edit_shop_cart_path(@shop_cart) %> |
<%= link_to 'Back', shop_carts_path %>-->