config/routes.rb
HelloWorldTests::Application.routes.draw do

  root :to => "home#index"
  get 'admin' => "auth_admin#index"

  controller :auth_sessions do
    get 'auth_login' => :new
    post 'auth_login' => :create
    delete 'auth_logout' => :destroy
    get 'auth_logout' => :destroy
  end

  resources :auth_users
  resources :shop_items, :google_map, :shop_carts
  resources :user_orders
  resources :cars
  resources :fb_users, :only => [:index]
  resources :frogs
  resources :my_test_scaffolds do
    get :who_bought_this, :on => :member
  end

  match 'svetik/home' => 'svetik#home'
  match 'say/hello' => 'say#hello'
  match 'say/goodbye' => 'say#goodbye'
  match 'my_store' => 'my_store#index'
  match 'resque_que' => 'resque_que#index'
  mount Resque::Server, :at => "/resque"
end

app/models/car.rb
class Car < ActiveRecord::Base

  validates :name, :presence => true

  state_machine :state, :initial => :stopped do 
    state :started
    state :stopped
    
    before_transition any => :stopped, :do => :stopping
    after_transition any => :started, :do => :starting
    
    event :stop_it do
      transition :started => :stopped
    end
    
    event :start_it do
      transition :stopped => :started
    end

  end
  
  def stopping
    Rails.logger.debug "Stopping"
  end
  
  def starting
    Rails.logger.debug "Starting"
  end

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cars }
    end
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
    @car = Car.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @car }
    end
  end

  # GET /cars/new
  # GET /cars/new.json
  def new
    @car = Car.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @car }
    end
  end

  # GET /cars/1/edit
  def edit
    @car = Car.find(params[:id])
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(params[:car])

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render json: @car, status: :created, location: @car }
      else
        format.html { render action: "new" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cars/1
  # PUT /cars/1.json
  def update
    @car = Car.find(params[:id])

    case params[:set_state]
    when 'start' then @car.start_it
    when 'stop' then @car.stop_it
    end

    respond_to do |format|
      if @car.update_attributes(params[:car])
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render json: %Q({"state": "#{@car.state}"}), status: :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car = Car.find(params[:id])
    @car.destroy

    respond_to do |format|
      format.html { redirect_to cars_url }
      format.json { head :ok }
    end
  end
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :options %><br />
    <%= f.text_field :options %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<%= javascript_include_tag :defaults, "car" %>
<%= stylesheet_link_tag "car" %>

<h1>Editing car</h1>

<%= render 'form' %>
<br/>
<span>
State: <span id="state"><%= @car.state %></span>&nbsp;&nbsp;&nbsp;&nbsp;
      <%= link_to "start", "#", :onclick => "update('state','" + car_path(@car) + "', 'start')", :class =>'nice_button' %>
      <%= link_to "stop", "#", :onclick => "update('state','" + car_path(@car) + "', 'stop')", :class =>'nice_button' %>
</span>
</br>
</br>
<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<%= stylesheet_link_tag "car", "nice_table" %>
<%= javascript_include_tag :defaults, "car" %>

<h1>Listing cars</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Options</th>
    <th>State</th>
    <th>Change state</th>
    <th></th>
  </tr>

<% @cars.each do |car| %>
  <tr>
    <td><%= car.name %></td>
    <td><%= car.options %></td>
    <td id="state_<%= car.id %>"><%= car.state %></td>
    <td>
      <%= link_to "start", "#", :onclick => "update('state_" + car.id.to_s + "','" + car_path(car) + "', 'start')", :class =>'nice_button' %>
      <%= link_to "stop", "#", :onclick => "update('state_" + car.id.to_s + "','" + car_path(car) + "', 'stop')", :class =>'nice_button' %>
    </td>
    <td class="default_links">
      <%= link_to 'Show', car %><br/>
      <%= link_to 'Edit', edit_car_path(car) %><br/>
      <%= link_to 'Destroy', car, confirm: 'Are you sure?', method: :delete %><br/>
    </td>
  </tr>
<% end %>
<div id='throbber'>
  <div style="text-align:center;">
    <img src="/images/throbber.gif" alt="Loading... please wait" title="Loading... please wait" />
  </div>
</div>
</table>

<br />

<%= link_to 'New Car', new_car_path %><br/>
<%= link_to "Back to Home", "/" %>

app/views/cars/new.html.erb
<h1>New car</h1>

Initial status:<br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;stopped<br/>
<%= render 'form' %>
<br/>
<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @car.name %>
</p>

<p>
  <b>Options:</b>
  <%= @car.options %>
</p>

<p>
  <b>State:</b>
  <%= @car.state %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>